// Code generated by mockery v2.14.0. DO NOT EDIT.

package extensions

import (
	mock "github.com/stretchr/testify/mock"
	jnigi "tekao.net/jnigi"
)

// MockIInterfaceHandler is an autogenerated mock type for the IInterfaceHandler type
type MockIInterfaceHandler[T comparable] struct {
	mock.Mock
}

// toGoRepresentation provides a mock function with given fields: env, object, dest
func (_m *MockIInterfaceHandler[T]) toGoRepresentation(env *jnigi.Env, object *jnigi.ObjectRef, dest *T) error {
	ret := _m.Called(env, object, dest)

	var r0 error
	if rf, ok := ret.Get(0).(func(*jnigi.Env, *jnigi.ObjectRef, *T) error); ok {
		r0 = rf(env, object, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// toJniRepresentation provides a mock function with given fields: env, value
func (_m *MockIInterfaceHandler[T]) toJniRepresentation(env *jnigi.Env, value T) (*jnigi.Env, error) {
	ret := _m.Called(env, value)

	var r0 *jnigi.Env
	if rf, ok := ret.Get(0).(func(*jnigi.Env, T) *jnigi.Env); ok {
		r0 = rf(env, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jnigi.Env)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*jnigi.Env, T) error); ok {
		r1 = rf(env, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockIInterfaceHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockIInterfaceHandler creates a new instance of MockIInterfaceHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockIInterfaceHandler[T comparable](t mockConstructorTestingTNewMockIInterfaceHandler) *MockIInterfaceHandler[T] {
	mock := &MockIInterfaceHandler[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
