// Code generated by mockery v2.14.0. DO NOT EDIT.

package gmx

import mock "github.com/stretchr/testify/mock"

// MockMBeanOperator is an autogenerated mock type for the MBeanOperator type
type MockMBeanOperator struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MockMBeanOperator) Close() {
	_m.Called()
}

// Connect provides a mock function with given fields: hostname, port
func (_m *MockMBeanOperator) Connect(hostname string, port int) {
	_m.Called(hostname, port)
}

// Initialize provides a mock function with given fields:
func (_m *MockMBeanOperator) Initialize() (*Client, error) {
	ret := _m.Called()

	var r0 *Client
	if rf, ok := ret.Get(0).(func() *Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockMBeanOperator interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockMBeanOperator creates a new instance of MockMBeanOperator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockMBeanOperator(t mockConstructorTestingTNewMockMBeanOperator) *MockMBeanOperator {
	mock := &MockMBeanOperator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
