// Code generated by mockery v2.14.0. DO NOT EDIT.

package gmx

import mock "github.com/stretchr/testify/mock"

// MockMBeanClient is an autogenerated mock type for the MBeanClient type
type MockMBeanClient struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MockMBeanClient) Close() {
	_m.Called()
}

// Initialize provides a mock function with given fields:
func (_m *MockMBeanClient) Initialize() {
	_m.Called()
}

type mockConstructorTestingTNewMockMBeanClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockMBeanClient creates a new instance of MockMBeanClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockMBeanClient(t mockConstructorTestingTNewMockMBeanClient) *MockMBeanClient {
	mock := &MockMBeanClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
