// Code generated by mockery v2.14.0. DO NOT EDIT.

package gmx

import (
	extensions "github.com/arinn1204/gmx/pkg/extensions"
	mock "github.com/stretchr/testify/mock"
)

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

// RegisterClassHandler provides a mock function with given fields: typeName, handler
func (_m *MockHandler) RegisterClassHandler(typeName string, handler extensions.IHandler) {
	_m.Called(typeName, handler)
}

// RegisterInterfaceHandler provides a mock function with given fields: typeName, handler
func (_m *MockHandler) RegisterInterfaceHandler(typeName string, handler extensions.InterfaceHandler) {
	_m.Called(typeName, handler)
}

type mockConstructorTestingTNewMockHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockHandler(t mockConstructorTestingTNewMockHandler) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
